# Site settings
title: Dawn of the dev
author: RÃ©mi San
email: remi.san@gmail.com

tags: [ "DDD", "PHP", "OOP" ]
description: A blog about tech discoveries, especially about DDD, CQRS and Event-Sourcing
keywords: OOP, DDD, CQRS, Event-Sourcing

baseurl: ""
url: "http://remi-san.github.io"

twitter_username: RemiSan
github_username:  remi-san
disqus_username:  remisan

google_analytics: UA-69261990-1

# Build settings
markdown: kramdown

permalink:   /:title.html
